let number1=8;
let number2=8;
console.log(number1-number2); 
console.log(number1 % number2); 
console.log(++number1); 
console.log(--number1); 
console.log(number1++);
let number3=8;
console.log(number3**3);
console.log(number3**10);
let number4=6;
let result=number4+4;
console.log(result);
let number5=6;
number5*=2;
console.log(number5);
let number6=5;
console.log(number6==5);
console.log(number6==7);
console.log(number6!=5);
console.log(number6<7);
console.log(number6>7);
console.log(number6<5);
console.log(number6>=2);
let number7=5;
console.log(number7);
let number8=66.8;
console.log(number8);
let name="dhansai";
console.log("name");
let sample=true;
console.log(sample);
let number9=6;
let number10=4;
console.log(number9<10 && number10<5);
console.log(number9<10 || number10<2);
console.log(!number9<10 ||number10<2); 
let name1 = 'dhan';
let name2 = 'sai';
let name3 = 'vaishu';
console.log(name1.length);
console.log(name1.slice(0,3));
console.log(name1.substring(0,2))
let text = "       Hello guys!        ";
let result1 = text.replace(/^\s+|\s+$/gm,'');
console.log(name3.toUpperCase())
console.log(name3.toLowerCase())
console.log(name1.concat(name3));
console.log(name3.replace("hii"));